[toolchain]
channel = "nightly-2025-10-06" # "nightly-2025-02-20"
# channel = "stage1"
components = [
    "rust-src",
    "rustc-dev",
    "llvm-tools-preview",
    "rust-analyzer",
    "clippy",
    "miri"
]
