[package]
name = "spec-trait-order"
version = "0.1.0"
edition = "2024"

[dependencies]
spec-trait-utils = { path = "../spec-trait-utils" }
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version = "2.0", features = ["full"] }
toml = "0.9.5"
glob = "0.3"

[dev-dependencies]
tempfile = "3"
