[package]
name = "spec-trait-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
spec-trait-macro = { path = "../spec-trait-macro" }

[build-dependencies]
spec-trait-order = { path = "../spec-trait-order" }
